### ISSUE TITLE
Excluding devices?

### ISSUE THREAD

**Issue by KarlssonH3** [Herlix/homebridge-plejd#12]
**Describe Your Problem:**
I'd like for my DIM-02 to show up in HomeKit but not my WPH-01 as I don't see why I would want it there in the first place, is it possible to exclude/disable devices in HB?

**Comment by Herlix** [comment]
Hey!

It is not possible for now. But I could add this feature.

**Comment by Herlix** [comment]
The 1.3.2 version should solve your issue 😄

**Comment by KarlssonH3** [comment]
Tackaaaaarrrrrr
