### ISSUE TITLE
Error during install homebridge

### ISSUE THREAD

**Issue by cumafo** [Herlix/homebridge-plejd#14]
**Describe The Bug:**
During installation there is this message:

node-pre-gyp ERR! install response status 404 Not Found on https://github.com/abandonware/node-bluetooth-hci-socket/releases/download/0.5.3-10/bluetooth_hci_socket-0.5.3-10-node-v108-linux-arm.tar.gz

**Expected behavior:**
not sure if this is critical
**Logs:**
Cannot find installatin logs

**Environment:**

* **Plugin Version**:
v1.3.4
* **Homebridge Version**: 
1.7.0

* **Operating System**
Raspbian

**Comment by Herlix** [comment]
Hi! 

Have you been able to install the addon? 

I'll look into this as soon as possible. 

It seems to be a standing issue in the BLE dependency that I'm using.

**Comment by cumafo** [comment]
Hello,

Yes I have it installed and working but not perfectly stable.
I had some issues with old plejd firmware on some devices (have quite a few) but once updated I managed to get control.
I had to do some tveaking but right now not able to find  out due to traveling.
Will check next week.
Nice software btw....
/C


-------- Original message --------
From: Alexander Herlin ***@***.***>
Date: 3/14/24 09:20 (GMT+01:00)
To: Herlix/homebridge-plejd ***@***.***>
Cc: Curt Lestrup ***@***.***>, Author ***@***.***>
Subject: Re: [Herlix/homebridge-plejd] Error during install homebridge (Issue #14)


Hi!

Have you been able to install the addon?

I'll look into this as soon as possible.

It seems to be a standing issue in the BLE dependency that I'm using.

**Comment by Herlix** [comment]
Sounds good that the install works :) 

I've had some stability issues, working on it getting them right. Sorry about this.
