### ISSUE TITLE
Work with DIM-01-2P

### ISSUE THREAD

**Issue by helangen** [Herlix/homebridge-plejd#6]
**Describe Your Problem:**

Do this work with the DIM-01-2P units? I get the following error using DIM-01 in the Plejd plugin for Homebridge.

**Logs:**

```
[7/12/2022, 7:55:00 PM] Error: ENODEV, No such device
    at Hci.init (/var/lib/homebridge/node_modules/homebridge-plejd/node_modules/@abandonware/noble/lib/hci-socket/hci.js:121:20)
    at NobleBindings.init (/var/lib/homebridge/node_modules/homebridge-plejd/node_modules/@abandonware/noble/lib/hci-socket/bindings.js:93:13)
    at /var/lib/homebridge/node_modules/homebridge-plejd/node_modules/@abandonware/noble/lib/noble.js:61:24
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
```

**Plugin Config:**

```json
{
    "crypto_key": "*redacted*",
    "devices": [
        {
            "name": "Spisestue",
            "model": "DIM-02",
            "identifier": 11
        }
    ],
    "platform": "Plejd"
}
```

**Screenshots:**

**Environment:**

* **Plugin Version**: v1.2.1
* **Homebridge Version**:   v.1.5.0
* **Node.js Version**:  v16.16.0
* **NPM Version**:  v5.8.0
* **Operating System**:  Raspbian

**Comment by Herlix** [comment]
Hey! 

I have not tested it with this unit. Though it might be possible to add support, I'll see what I can do about it. 

I have not had time to look at this project in a while sadly, but my intent is to take care of some bugs as soon as possible.

**Comment by helangen** [comment]
I actually got it working using the DIM-01. It seems like these are quite similar. My problem was missing BT in the RasPi 2. 🙈

**Comment by Herlix** [comment]
I've added the DIM-01-2P as an input choice, it'll be handled just as a DIM-01:)
